<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/05/18 19:20:55
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
