<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/06/06 02:28:38
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
