<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/05/29 03:50:35
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
